const popupDeatils = {
  Home: {
    heading: "Home",
    check1: `Living Room`,
    check2: "Bedroom",
    check3: "Kids room",
    check4: "Kids room",
    check5: "Kitchen",
    check6: "Bathroom",
    check7: "Toilet",
    check8: "Garden",
    check9: "Terrace / Balcony ",
    check10: "Driveway",
    check11: "Storage",
    check12: "Garage",
  },

  Museum: {
    heading: "Museum",
    check1: "Reception",
    check2: "",
    check3: "",
    check4: "",
    check5: "",
    check6: "",
    check7: "",
    check8: "",
    check9: "",
    check10: "",
    check11: "",
    check12: "",
    check13: "",
    check14: "",
    check15: "",
    check16: "",
    check17: "",
    check18: "",
    check19: "",
    check20: "",
    check21: "",
    check22: "",
    check23: "",
    check24: "",
    check25: "",
  },
};

export default popupDeatils;
